name: Second Workflow
on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Second Workflow
        run : echo "This is Second Workflow"
